In [3]:
from sqlalchemy import create_engine

In [4]:
# Database credentials
postgres_user = 'dsbc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'dvdrentals'

engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(
    postgres_user, postgres_pw, postgres_host, postgres_port, postgres_db))

In [5]:
# Use the connection to execute some SQL
rentals = engine.execute('select * from rental limit 10')

# no need for an open connection, as we're only doing a single query
engine.dispose()

# Process the results
for row in rentals:
  print(row)

(2, datetime.datetime(2005, 5, 24, 22, 54, 33), 1525, 459, datetime.datetime(2005, 5, 28, 19, 40, 33), 1, datetime.datetime(2006, 2, 16, 2, 30, 53))
(3, datetime.datetime(2005, 5, 24, 23, 3, 39), 1711, 408, datetime.datetime(2005, 6, 1, 22, 12, 39), 1, datetime.datetime(2006, 2, 16, 2, 30, 53))
(4, datetime.datetime(2005, 5, 24, 23, 4, 41), 2452, 333, datetime.datetime(2005, 6, 3, 1, 43, 41), 2, datetime.datetime(2006, 2, 16, 2, 30, 53))
(5, datetime.datetime(2005, 5, 24, 23, 5, 21), 2079, 222, datetime.datetime(2005, 6, 2, 4, 33, 21), 1, datetime.datetime(2006, 2, 16, 2, 30, 53))
(6, datetime.datetime(2005, 5, 24, 23, 8, 7), 2792, 549, datetime.datetime(2005, 5, 27, 1, 32, 7), 1, datetime.datetime(2006, 2, 16, 2, 30, 53))
(7, datetime.datetime(2005, 5, 24, 23, 11, 53), 3995, 269, datetime.datetime(2005, 5, 29, 20, 34, 53), 2, datetime.datetime(2006, 2, 16, 2, 30, 53))
(8, datetime.datetime(2005, 5, 24, 23, 31, 46), 2346, 239, datetime.datetime(2005, 5, 27, 23, 33, 46), 2, datetime.datetime(2006, 2, 16, 2, 30, 53))
(9, datetime.datetime(2005, 5, 25, 0, 0, 40), 2580, 126, datetime.datetime(2005, 5, 28, 0, 22, 40), 1, datetime.datetime(2006, 2, 16, 2, 30, 53))
(10, datetime.datetime(2005, 5, 25, 0, 2, 21), 1824, 399, datetime.datetime(2005, 5, 31, 22, 44, 21), 2, datetime.datetime(2006, 2, 16, 2, 30, 53))
(11, datetime.datetime(2005, 5, 25, 0, 9, 2), 4443, 142, datetime.datetime(2005, 6, 2, 20, 56, 2), 2, datetime.datetime(2006, 2, 16, 2, 30, 53))

In [6]:
#Question1 How many movies are released for each rating?

sql = '''
  SELECT COUNT(DISTINCT film_id),rating
  FROM film
  GROUP BY rating;
'''

results = engine.execute(sql)
engine.dispose()
rows = results.fetchall()

# print some results just to see what we got
for row in rows:
  print(row)

(178, 'G')
(194, 'PG')
(223, 'PG-13')
(195, 'R')
(210, 'NC-17')

In [7]:
# Question 2 What is the average rental duration for each rating?
sql_2='''
SELECT AVG(rental_duration),rating
FROM film
GROUP BY rating;'''

results_2=engine.execute(sql_2)
engine.dispose()
rows2=results_2.fetchall()

for row in rows2:
  print(row)

(Decimal('4.7743589743589744'), 'R')
(Decimal('5.1428571428571429'), 'NC-17')
(Decimal('5.0824742268041237'), 'PG')
(Decimal('5.0538116591928251'), 'PG-13')
(Decimal('4.8370786516853933'), 'G')

In [28]:
#Question 3 What is the mean movie length? Calculate this by defining a function.

sql_3='''
SELECT length
FROM film
'''

lengths=engine.execute(sql_3)
engine.dispose()
rows3=lengths.fetchall()
print(rows3)
type(rows3)
lengths = [x[0] for x in rows3]
print(lengths)

[(86,), (48,), (50,), (117,), (130,), (169,), (62,), (54,), (114,), (63,), (126,), (136,), (104,), (150,), (94,), (46,), (180,), (82,), (57,), (113,), (79,), (129,), (85,), (92,), (181,), (74,), (86,), (179,), (91,), (168,), (82,), (92,), (119,), (153,), (62,), (147,), (127,), (121,), (68,), (99,), (148,), (137,), (170,), (170,), (113,), (83,), (108,), (153,), (118,), (162,), (182,), (75,), (173,), (87,), (113,), (65,), (129,), (90,), (122,), (160,), (89,), (175,), (106,), (73,), (151,), (100,), (53,), (77,), (122,), (85,), (142,), (100,), (93,), (150,), (162,), (163,), (103,), (61,), (85,), (114,), (148,), (103,), (71,), (50,), (102,), (63,), (121,), (76,), (179,), (63,), (63,), (98,), (72,), (121,), (176,), (123,), (169,), (56,), (73,), (136,), (161,), (73,), (60,), (133,), (119,), (125,), (61,), (63,), (67,), (89,), (53,), (52,), (120,), (75,), (61,), (167,), (70,), (135,), (85,), (176,), (92,), (151,), (114,), (85,), (163,), (61,), (179,), (112,), (183,), (179,), (110,), (152,), (114,), (117,), (51,), (70,), (146,), (66,), (71,), (114,), (87,), (185,), (122,), (142,), (61,), (124,), (107,), (101,), (132,), (150,), (101,), (143,), (90,), (165,), (81,), (150,), (164,), (143,), (124,), (58,), (65,), (70,), (95,), (139,), (55,), (70,), (149,), (109,), (67,), (76,), (120,), (59,), (112,), (65,), (180,), (122,), (87,), (172,), (115,), (173,), (184,), (166,), (185,), (112,), (92,), (146,), (64,), (57,), (136,), (139,), (172,), (143,), (50,), (153,), (104,), (112,), (69,), (112,), (184,), (56,), (133,), (176,), (161,), (84,), (106,), (58,), (144,), (121,), (89,), (99,), (130,), (165,), (185,), (59,), (57,), (113,), (120,), (122,), (51,), (106,), (100,), (64,), (76,), (81,), (76,), (56,), (88,), (143,), (87,), (107,), (63,), (147,), (141,), (94,), (68,), (100,), (47,), (57,), (122,), (120,), (125,), (68,), (49,), (139,), (177,), (154,), (47,), (177,), (176,), (170,), (133,), (135,), (61,), (159,), (175,), (178,), (110,), (96,), (116,), (132,), (171,), (119,), (154,), (101,), (168,), (141,), (140,), (96,), (98,), (85,), (148,), (153,), (107,), (67,), (85,), (115,), (126,), (155,), (152,), (177,), (143,), (92,), (85,), (77,), (51,), (158,), (176,), (167,), (66,), (163,), (174,), (51,), (167,), (138,), (97,), (178,), (122,), (172,), (144,), (102,), (155,), (131,), (58,), (130,), (91,), (104,), (77,), (142,), (98,), (158,), (72,), (75,), (118,), (91,), (156,), (173,), (148,), (103,), (125,), (80,), (123,), (100,), (179,), (148,), (145,), (69,), (158,), (131,), (63,), (112,), (90,), (159,), (126,), (65,), (133,), (99,), (73,), (51,), (111,), (183,), (82,), (83,), (94,), (178,), (161,), (128,), (119,), (86,), (185,), (80,), (106,), (176,), (125,), (85,), (101,), (102,), (114,), (163,), (173,), (103,), (89,), (115,), (54,), (73,), (154,), (93,), (153,), (84,), (56,), (108,), (129,), (140,), (156,), (117,), (85,), (155,), (135,), (93,), (166,), (176,), (150,), (137,), (111,), (49,), (139,), (53,), (100,), (70,), (127,), (84,), (146,), (51,), (47,), (146,), (108,), (62,), (107,), (47,), (100,), (72,), (168,), (52,), (121,), (107,), (76,), (181,), (47,), (69,), (59,), (48,), (49,), (102,), (169,), (75,), (84,), (110,), (93,), (157,), (141,), (128,), (78,), (136,), (69,), (149,), (88,), (185,), (103,), (141,), (84,), (49,), (176,), (139,), (95,), (139,), (181,), (122,), (109,), (68,), (151,), (105,), (125,), (65,), (49,), (83,), (100,), (150,), (131,), (172,), (119,), (84,), (160,), (122,), (178,), (180,), (103,), (167,), (157,), (135,), (74,), (178,), (123,), (78,), (116,), (107,), (59,), (63,), (181,), (97,), (46,), (79,), (84,), (174,), (181,), (174,), (135,), (130,), (118,), (112,), (128,), (84,), (58,), (102,), (171,), (172,), (60,), (59,), (124,), (105,), (54,), (121,), (74,), (134,), (92,), (120,), (169,), (179,), (54,), (161,), (184,), (163,), (141,), (71,), (171,), (46,), (46,), (67,), (113,), (144,), (78,), (181,), (175,), (110,), (153,), (69,), (113,), (59,), (167,), (140,), (138,), (91,), (147,), (137,), (174,), (50,), (140,), (120,), (85,), (155,), (67,), (108,), (137,), (80,), (98,), (70,), (181,), (65,), (75,), (162,), (152,), (97,), (74,), (52,), (116,), (147,), (178,), (98,), (117,), (53,), (171,), (74,), (138,), (130,), (136,), (159,), (133,), (127,), (177,), (71,), (114,), (62,), (123,), (151,), (165,), (161,), (56,), (72,), (80,), (77,), (147,), (104,), (161,), (64,), (105,), (86,), (48,), (122,), (64,), (142,), (149,), (166,), (59,), (162,), (164,), (180,), (105,), (60,), (77,), (175,), (74,), (135,), (182,), (107,), (158,), (126,), (83,), (171,), (184,), (57,), (103,), (166,), (79,), (146,), (53,), (160,), (157,), (160,), (50,), (166,), (185,), (129,), (73,), (180,), (92,), (178,), (180,), (92,), (50,), (132,), (161,), (131,), (75,), (159,), (75,), (149,), (83,), (57,), (67,), (172,), (128,), (48,), (64,), (145,), (54,), (48,), (58,), (161,), (131,), (156,), (92,), (102,), (76,), (120,), (118,), (115,), (118,), (169,), (129,), (148,), (85,), (144,), (84,), (126,), (102,), (93,), (109,), (128,), (48,), (121,), (109,), (107,), (157,), (118,), (99,), (65,), (175,), (145,), (160,), (80,), (74,), (48,), (99,), (82,), (118,), (99,), (60,), (137,), (136,), (77,), (50,), (103,), (100,), (134,), (60,), (173,), (132,), (84,), (138,), (61,), (137,), (185,), (159,), (179,), (115,), (98,), (144,), (114,), (53,), (71,), (106,), (115,), (155,), (89,), (100,), (121,), (88,), (163,), (177,), (112,), (147,), (120,), (154,), (82,), (74,), (73,), (147,), (136,), (97,), (73,), (182,), (179,), (182,), (123,), (82,), (110,), (167,), (61,), (117,), (63,), (177,), (46,), (153,), (58,), (149,), (158,), (102,), (134,), (102,), (178,), (145,), (153,), (81,), (101,), (60,), (89,), (162,), (118,), (171,), (109,), (153,), (145,), (181,), (101,), (48,), (150,), (99,), (80,), (106,), (125,), (73,), (110,), (154,), (154,), (75,), (150,), (182,), (84,), (183,), (102,), (151,), (147,), (104,), (137,), (80,), (112,), (182,), (110,), (90,), (158,), (109,), (54,), (98,), (127,), (60,), (93,), (47,), (80,), (113,), (125,), (79,), (67,), (167,), (154,), (139,), (52,), (111,), (135,), (67,), (74,), (51,), (126,), (152,), (132,), (179,), (129,), (64,), (137,), (87,), (84,), (156,), (147,), (60,), (50,), (184,), (110,), (74,), (62,), (185,), (180,), (165,), (184,), (184,), (169,), (143,), (52,), (165,), (124,), (141,), (79,), (138,), (149,), (138,), (175,), (134,), (151,), (112,), (136,), (85,), (112,), (130,), (75,), (181,), (113,), (143,), (140,), (48,), (93,), (160,), (94,), (57,), (163,), (151,), (103,), (139,), (119,), (132,), (73,), (144,), (127,), (114,), (93,), (111,), (53,), (141,), (92,), (135,), (48,), (58,), (114,), (47,), (123,), (176,), (185,), (108,), (155,), (173,), (91,), (64,), (74,), (148,), (152,), (71,), (99,), (53,), (88,), (179,), (184,), (135,), (53,), (111,), (172,), (69,), (104,), (91,), (68,), (142,), (157,), (179,), (152,), (144,), (136,), (142,), (170,), (139,), (71,), (132,), (171,), (168,), (110,), (102,), (87,), (64,), (52,), (115,), (61,), (92,), (80,), (152,), (152,), (82,), (62,), (172,), (107,), (78,), (129,), (164,), (120,), (174,), (84,), (128,), (145,), (48,), (73,), (126,), (122,), (142,), (123,), (85,), (173,), (90,), (64,), (145,), (174,), (76,), (179,), (164,), (144,), (59,), (139,), (157,), (132,), (78,), (152,), (112,), (73,), (135,), (107,), (80,), (178,), (83,), (128,), (161,), (85,), (78,), (61,), (112,), (70,), (134,), (79,), (159,), (52,), (109,), (59,), (183,), (181,), (137,), (111,), (85,), (98,), (100,), (75,), (55,), (126,), (105,), (126,), (111,), (85,), (116,), (139,), (74,), (171,), (185,), (176,), (178,), (100,), (86,), (183,), (179,), (105,), (101,), (50,)]
[86, 48, 50, 117, 130, 169, 62, 54, 114, 63, 126, 136, 104, 150, 94, 46, 180, 82, 57, 113, 79, 129, 85, 92, 181, 74, 86, 179, 91, 168, 82, 92, 119, 153, 62, 147, 127, 121, 68, 99, 148, 137, 170, 170, 113, 83, 108, 153, 118, 162, 182, 75, 173, 87, 113, 65, 129, 90, 122, 160, 89, 175, 106, 73, 151, 100, 53, 77, 122, 85, 142, 100, 93, 150, 162, 163, 103, 61, 85, 114, 148, 103, 71, 50, 102, 63, 121, 76, 179, 63, 63, 98, 72, 121, 176, 123, 169, 56, 73, 136, 161, 73, 60, 133, 119, 125, 61, 63, 67, 89, 53, 52, 120, 75, 61, 167, 70, 135, 85, 176, 92, 151, 114, 85, 163, 61, 179, 112, 183, 179, 110, 152, 114, 117, 51, 70, 146, 66, 71, 114, 87, 185, 122, 142, 61, 124, 107, 101, 132, 150, 101, 143, 90, 165, 81, 150, 164, 143, 124, 58, 65, 70, 95, 139, 55, 70, 149, 109, 67, 76, 120, 59, 112, 65, 180, 122, 87, 172, 115, 173, 184, 166, 185, 112, 92, 146, 64, 57, 136, 139, 172, 143, 50, 153, 104, 112, 69, 112, 184, 56, 133, 176, 161, 84, 106, 58, 144, 121, 89, 99, 130, 165, 185, 59, 57, 113, 120, 122, 51, 106, 100, 64, 76, 81, 76, 56, 88, 143, 87, 107, 63, 147, 141, 94, 68, 100, 47, 57, 122, 120, 125, 68, 49, 139, 177, 154, 47, 177, 176, 170, 133, 135, 61, 159, 175, 178, 110, 96, 116, 132, 171, 119, 154, 101, 168, 141, 140, 96, 98, 85, 148, 153, 107, 67, 85, 115, 126, 155, 152, 177, 143, 92, 85, 77, 51, 158, 176, 167, 66, 163, 174, 51, 167, 138, 97, 178, 122, 172, 144, 102, 155, 131, 58, 130, 91, 104, 77, 142, 98, 158, 72, 75, 118, 91, 156, 173, 148, 103, 125, 80, 123, 100, 179, 148, 145, 69, 158, 131, 63, 112, 90, 159, 126, 65, 133, 99, 73, 51, 111, 183, 82, 83, 94, 178, 161, 128, 119, 86, 185, 80, 106, 176, 125, 85, 101, 102, 114, 163, 173, 103, 89, 115, 54, 73, 154, 93, 153, 84, 56, 108, 129, 140, 156, 117, 85, 155, 135, 93, 166, 176, 150, 137, 111, 49, 139, 53, 100, 70, 127, 84, 146, 51, 47, 146, 108, 62, 107, 47, 100, 72, 168, 52, 121, 107, 76, 181, 47, 69, 59, 48, 49, 102, 169, 75, 84, 110, 93, 157, 141, 128, 78, 136, 69, 149, 88, 185, 103, 141, 84, 49, 176, 139, 95, 139, 181, 122, 109, 68, 151, 105, 125, 65, 49, 83, 100, 150, 131, 172, 119, 84, 160, 122, 178, 180, 103, 167, 157, 135, 74, 178, 123, 78, 116, 107, 59, 63, 181, 97, 46, 79, 84, 174, 181, 174, 135, 130, 118, 112, 128, 84, 58, 102, 171, 172, 60, 59, 124, 105, 54, 121, 74, 134, 92, 120, 169, 179, 54, 161, 184, 163, 141, 71, 171, 46, 46, 67, 113, 144, 78, 181, 175, 110, 153, 69, 113, 59, 167, 140, 138, 91, 147, 137, 174, 50, 140, 120, 85, 155, 67, 108, 137, 80, 98, 70, 181, 65, 75, 162, 152, 97, 74, 52, 116, 147, 178, 98, 117, 53, 171, 74, 138, 130, 136, 159, 133, 127, 177, 71, 114, 62, 123, 151, 165, 161, 56, 72, 80, 77, 147, 104, 161, 64, 105, 86, 48, 122, 64, 142, 149, 166, 59, 162, 164, 180, 105, 60, 77, 175, 74, 135, 182, 107, 158, 126, 83, 171, 184, 57, 103, 166, 79, 146, 53, 160, 157, 160, 50, 166, 185, 129, 73, 180, 92, 178, 180, 92, 50, 132, 161, 131, 75, 159, 75, 149, 83, 57, 67, 172, 128, 48, 64, 145, 54, 48, 58, 161, 131, 156, 92, 102, 76, 120, 118, 115, 118, 169, 129, 148, 85, 144, 84, 126, 102, 93, 109, 128, 48, 121, 109, 107, 157, 118, 99, 65, 175, 145, 160, 80, 74, 48, 99, 82, 118, 99, 60, 137, 136, 77, 50, 103, 100, 134, 60, 173, 132, 84, 138, 61, 137, 185, 159, 179, 115, 98, 144, 114, 53, 71, 106, 115, 155, 89, 100, 121, 88, 163, 177, 112, 147, 120, 154, 82, 74, 73, 147, 136, 97, 73, 182, 179, 182, 123, 82, 110, 167, 61, 117, 63, 177, 46, 153, 58, 149, 158, 102, 134, 102, 178, 145, 153, 81, 101, 60, 89, 162, 118, 171, 109, 153, 145, 181, 101, 48, 150, 99, 80, 106, 125, 73, 110, 154, 154, 75, 150, 182, 84, 183, 102, 151, 147, 104, 137, 80, 112, 182, 110, 90, 158, 109, 54, 98, 127, 60, 93, 47, 80, 113, 125, 79, 67, 167, 154, 139, 52, 111, 135, 67, 74, 51, 126, 152, 132, 179, 129, 64, 137, 87, 84, 156, 147, 60, 50, 184, 110, 74, 62, 185, 180, 165, 184, 184, 169, 143, 52, 165, 124, 141, 79, 138, 149, 138, 175, 134, 151, 112, 136, 85, 112, 130, 75, 181, 113, 143, 140, 48, 93, 160, 94, 57, 163, 151, 103, 139, 119, 132, 73, 144, 127, 114, 93, 111, 53, 141, 92, 135, 48, 58, 114, 47, 123, 176, 185, 108, 155, 173, 91, 64, 74, 148, 152, 71, 99, 53, 88, 179, 184, 135, 53, 111, 172, 69, 104, 91, 68, 142, 157, 179, 152, 144, 136, 142, 170, 139, 71, 132, 171, 168, 110, 102, 87, 64, 52, 115, 61, 92, 80, 152, 152, 82, 62, 172, 107, 78, 129, 164, 120, 174, 84, 128, 145, 48, 73, 126, 122, 142, 123, 85, 173, 90, 64, 145, 174, 76, 179, 164, 144, 59, 139, 157, 132, 78, 152, 112, 73, 135, 107, 80, 178, 83, 128, 161, 85, 78, 61, 112, 70, 134, 79, 159, 52, 109, 59, 183, 181, 137, 111, 85, 98, 100, 75, 55, 126, 105, 126, 111, 85, 116, 139, 74, 171, 185, 176, 178, 100, 86, 183, 179, 105, 101, 50]

In [29]:
# Calculate mean of the movie length

def mean(numbers):
  total_sum = 0;  # initialize the sum to zero
  for n in numbers:
    total_sum += n # add up the numbers in the array
  count = len(numbers)   # find the length of the array
  avg = total_sum / count  # calculate the mean
  return avg  # return the result

print('The mean of the movie lengths is {}'.format(mean(lengths)))

The mean of the movie lengths is 115.272

In [33]:
#Question 4  What is the median movie length? Calculate this by defining a function.
import math

def median(numbers):
    numbers.sort()
    count=len(numbers)
    is_even = count % 2 == 0 #result is true or false
    
    if is_even==True:
      middle=math.floor(count/2)
      a=numbers[middle]
      b=numbers[middle+1]
      avg=(a+b)/2
    else:
        avg=numbers[math.floor(count/2)]
    return avg
    

print('The median of the charges is {}'.format(median(lengths)))

The median of the charges is 114.0

In [38]:
# Question 5 Calculate the standard deviation of the movie lengths. Calculate this by defining a function.
def std(numbers):
  mean_length=mean(numbers)
  length_number=len(numbers)
  sum_diff=0
  for i in numbers:
    diff=i-mean_length
    squared=math.pow(diff,2)
    sum_diff+=squared
  std=math.sqrt(sum_diff/(length_number-1))
  return std
    

print('The standard deviation of the charges is {}'.format(std(lengths)))

The standard deviation of the charges is 40.42633181855988